In [134]:
# Step 1  → Import Libraries
# Step 2  → Load Dataset
# Step 3  → Shape
# Step 4  → Copy Dataset
# Step 5  → Info
# Step 6  → Missing Value Report
# Step 7  → High Missing Analysis
# Step 8  → Review High Missing Columns
# Step 9  → Remove Unnecessary Columns
# Step 10 → Remove Duplicates
# Step 11 → Convert Date Columns
# Step 12 → Handle Missing Values
# Step 13 → Validate Dataset
# ✅ Step 14 → Select Final Business Columns
# Step 15 → Save clean_loan.csv


import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows",100)

In [3]:
df = pd.read_csv(
    r"C:\Users\henry\OneDrive\Desktop\LendingClub-Data-Pipeline\data\raw\loan.csv",
    low_memory=False
)

In [13]:
print(df.shape)

(2260668, 145)

In [ ]:

loan_df = df.copy()

MemoryError: Unable to allocate 1.77 GiB for an array with shape (105, 2260668) and data type float64

In [17]:
loan_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2260668 entries, 0 to 2260667
Columns: 145 entries, id to settlement_term
dtypes: float64(105), int64(4), str(36)
memory usage: 2.4 GB

In [24]:
missing = pd.DataFrame({
    "missing_value" : loan_df.isnull().sum(),
    "missing %" : (loan_df.isnull().mean()*100).round(2)
})


missing = missing.sort_values(
    by="missing_value",
    ascending=False
)

missing.head(30)

                                            missing_value  missing %
id                                                2260668     100.00
member_id                                         2260668     100.00
url                                               2260668     100.00
orig_projected_additional_accrued_interest        2252242      99.63
hardship_amount                                   2250055      99.53
hardship_dpd                                      2250055      99.53
hardship_loan_status                              2250055      99.53
deferral_term                                     2250055      99.53
hardship_end_date                                 2250055      99.53
hardship_status                                   2250055      99.53
hardship_start_date                               2250055      99.53
hardship_reason                                   2250055      99.53
hardship_type                                     2250055      99.53
hardship_payoff_balance_amount                    2250055      99.53
hardship_last_payment_amount                      2250055      99.53
hardship_length                                   2250055      99.53
payment_plan_start_date                           2250055      99.53
debt_settlement_flag_date                         2227612      98.54
settlement_term                                   2227612      98.54
settlement_amount                                 2227612      98.54
settlement_date                                   2227612      98.54
settlement_percentage                             2227612      98.54
settlement_status                                 2227612      98.54
sec_app_mths_since_last_major_derog               2224726      98.41
sec_app_revol_util                                2154484      95.30
revol_bal_joint                                   2152648      95.22
sec_app_earliest_cr_line                          2152647      95.22
sec_app_mort_acc                                  2152647      95.22
sec_app_open_act_il                               2152647      95.22
sec_app_num_rev_accts                             2152647      95.22

In [27]:
high_missing = missing[missing["missing %"] > 80]

high_missing

                                            missing_value  missing %
id                                                2260668     100.00
member_id                                         2260668     100.00
url                                               2260668     100.00
orig_projected_additional_accrued_interest        2252242      99.63
hardship_amount                                   2250055      99.53
hardship_dpd                                      2250055      99.53
hardship_loan_status                              2250055      99.53
deferral_term                                     2250055      99.53
hardship_end_date                                 2250055      99.53
hardship_status                                   2250055      99.53
hardship_start_date                               2250055      99.53
hardship_reason                                   2250055      99.53
hardship_type                                     2250055      99.53
hardship_payoff_balance_amount                    2250055      99.53
hardship_last_payment_amount                      2250055      99.53
hardship_length                                   2250055      99.53
payment_plan_start_date                           2250055      99.53
debt_settlement_flag_date                         2227612      98.54
settlement_term                                   2227612      98.54
settlement_amount                                 2227612      98.54
settlement_date                                   2227612      98.54
settlement_percentage                             2227612      98.54
settlement_status                                 2227612      98.54
sec_app_mths_since_last_major_derog               2224726      98.41
sec_app_revol_util                                2154484      95.30
revol_bal_joint                                   2152648      95.22
sec_app_earliest_cr_line                          2152647      95.22
sec_app_mort_acc                                  2152647      95.22
sec_app_open_act_il                               2152647      95.22
sec_app_num_rev_accts                             2152647      95.22
sec_app_inq_last_6mths                            2152647      95.22
sec_app_chargeoff_within_12_mths                  2152647      95.22
sec_app_open_acc                                  2152647      95.22
sec_app_collections_12_mths_ex_med                2152647      95.22
verification_status_joint                         2144938      94.88
dti_joint                                         2139962      94.66
annual_inc_joint                                  2139958      94.66
desc                                              2134603      94.42
mths_since_last_record                            1901512      84.11

In [29]:
print( 
      "Columns having more than 80% missing values :",
      high_missing.shape[0])

Columns having more than 80% missing values : 39

In [31]:
high_missing_cols = high_missing.index.tolist()

high_missing_cols

['id',
 'member_id',
 'url',
 'orig_projected_additional_accrued_interest',
 'hardship_amount',
 'hardship_dpd',
 'hardship_loan_status',
 'deferral_term',
 'hardship_end_date',
 'hardship_status',
 'hardship_start_date',
 'hardship_reason',
 'hardship_type',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'hardship_length',
 'payment_plan_start_date',
 'debt_settlement_flag_date',
 'settlement_term',
 'settlement_amount',
 'settlement_date',
 'settlement_percentage',
 'settlement_status',
 'sec_app_mths_since_last_major_derog',
 'sec_app_revol_util',
 'revol_bal_joint',
 'sec_app_earliest_cr_line',
 'sec_app_mort_acc',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_inq_last_6mths',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_open_acc',
 'sec_app_collections_12_mths_ex_med',
 'verification_status_joint',
 'dti_joint',
 'annual_inc_joint',
 'desc',
 'mths_since_last_record']

In [32]:
loan_df.drop(
    columns=high_missing_cols,
    inplace=True
)

In [34]:
loan_df.shape

(2260668, 106)

In [36]:
drop_cols = [

    "id",
    "member_id",
    "url",
    "desc",
    "policy_code"

]

In [41]:
loan_df.drop(
    columns=drop_cols,
    inplace=True,
    errors="ignore"
)

# errors="ignore"

# Agar column already remove ho gaya ho to error nahi aayega.

loan_df.shape

(2260668, 105)

In [44]:
loan_df.duplicated().sum()

np.int64(0)

In [47]:
loan_df.dtypes.value_counts()

float64    79
str        23
int64       3
Name: count, dtype: int64

In [75]:
date_cols = [
    "issue_d",
    "last_pymnt_d",
    "next_pymnt_d",
    "last_credit_pull_d"
]

In [77]:
loan_df[date_cols].dtypes

issue_d               datetime64[us]
last_pymnt_d          datetime64[us]
next_pymnt_d          datetime64[us]
last_credit_pull_d    datetime64[us]
dtype: object

In [79]:
numeric_cols = loan_df.select_dtypes(
    include=np.number
).columns

numeric_cols

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'int_rate', 'installment', 'annual_inc', 'url', 'dti',
       ...
       'deferral_term', 'hardship_amount', 'hardship_length', 'hardship_dpd',
       'orig_projected_additional_accrued_interest',
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='str', length=102)

In [86]:
loan_df.isnull().sum().sort_values(ascending=False)

id                                            2260668
member_id                                     2260668
url                                           2260668
orig_projected_additional_accrued_interest    2252242
hardship_amount                               2250055
                                               ...
total_rec_int                                       0
collection_recovery_fee                             0
hardship_flag                                       0
disbursement_method                                 0
debt_settlement_flag                                0
Length: 145, dtype: int64

In [100]:
num_cols = loan_df.select_dtypes(include=["number"]).columns




for col in num_cols:
    loan_df[col] = loan_df[col].fillna(loan_df[col].median())

In [97]:
loan_df.isnull().sum().sort_values(ascending=False)

id                             2260668
member_id                      2260668
url                            2260668
mths_since_recent_bc_dlq       1740967
mths_since_last_major_derog    1679893
                                ...
settlement_status                    0
settlement_date                      0
settlement_amount                    0
settlement_percentage                0
settlement_term                      0
Length: 145, dtype: int64

In [98]:
cat_cols = loan_df.select_dtypes(include=["object"]).columns

for col in cat_cols:
    loan_df[col] = loan_df[col].fillna("unknown")

C:\Users\henry\AppData\Local\Temp\ipykernel_13456\277998835.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = loan_df.select_dtypes(include=["object"]).columns

In [102]:
loan_df.isnull().sum().sort_values(ascending=False)

id                             2260668
member_id                      2260668
url                            2260668
mths_since_recent_bc_dlq       1740967
mths_since_last_major_derog    1679893
                                ...
settlement_status                    0
settlement_date                      0
settlement_amount                    0
settlement_percentage                0
settlement_term                      0
Length: 145, dtype: int64

In [104]:
print("Shape :", loan_df.shape)

Shape : (2260668, 145)

In [106]:
print("\nData Types")
print(loan_df.dtypes)

Data Types
id                       float64
member_id                float64
loan_amnt                  int64
funded_amnt                int64
funded_amnt_inv          float64
                          ...
settlement_status            str
settlement_date              str
settlement_amount        float64
settlement_percentage    float64
settlement_term          float64
Length: 145, dtype: object

In [107]:
print("\nMissing Values")
print(loan_df.isnull().sum().sort_values(ascending=False))

Missing Values
id                             2260668
member_id                      2260668
url                            2260668
mths_since_recent_bc_dlq       1740967
mths_since_last_major_derog    1679893
                                ...
settlement_status                    0
settlement_date                      0
settlement_amount                    0
settlement_percentage                0
settlement_term                      0
Length: 145, dtype: int64

In [108]:
print("\nDuplicate Rows :", loan_df.duplicated().sum())

Duplicate Rows : 0

In [109]:
print("\nMemory Usage (MB):")
print(
    round(
        loan_df.memory_usage(deep=True).sum() / 1024**2,
        2
    ),
    "MB"
)

Memory Usage (MB):
5831.44 MB

In [111]:
print("\nSummary Statistics")
display(loan_df.describe().T)

Summary Statistics

,count,mean,min,25%,50%,75%,max,std
id,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
member_id,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loan_amnt,2260668.0,15046.931228,500.0,8000.0,12900.0,20000.0,40000.0,9190.245488
funded_amnt,2260668.0,15041.664057,500.0,8000.0,12875.0,20000.0,40000.0,9188.413022
funded_amnt_inv,2260668.0,15023.437624,0.0,8000.0,12800.0,20000.0,40000.0,9192.331807
...,...,...,...,...,...,...,...,...
hardship_payoff_balance_amount,2260668.0,10051.655432,55.73,10044.22,10044.22,10044.22,40306.41,532.86052
hardship_last_payment_amount,2260668.0,133.175041,0.01,132.89,132.89,132.89,1407.86,14.231986
settlement_amount,2260668.0,4185.397243,44.21,4172.855,4172.855,4172.855,33601.0,458.160974
settlement_percentage,2260668.0,45.040585,0.2,45.0,45.0,45.0,521.35,0.947619
settlement_term,2260668.0,13.987551,0.0,14.0,14.0,14.0,181.0,0.995878

In [112]:
# Loan Information
loan_columns = [
    "loan_amnt",
    "funded_amnt",
    "funded_amnt_inv",
    "term",
    "int_rate",
    "installment",
    "purpose",
    "loan_status"
]

# Customer Information
customer_columns = [
    "emp_title",
    "emp_length",
    "home_ownership",
    "annual_inc",
    "verification_status",
    "application_type",
    "addr_state",
    "zip_code"
]

# Credit Profile
credit_columns = [
    "grade",
    "sub_grade",
    "dti",
    "delinq_2yrs",
    "earliest_cr_line",
    "inq_last_6mths",
    "open_acc",
    "pub_rec",
    "revol_bal",
    "revol_util",
    "total_acc",
    "acc_now_delinq"
]

# Payment Information
payment_columns = [
    "out_prncp",
    "total_pymnt",
    "total_rec_prncp",
    "total_rec_int",
    "recoveries",
    "last_pymnt_d",
    "last_pymnt_amnt",
    "last_credit_pull_d",
    "issue_d",
    "total_rev_hi_lim"
]

# Final Selected Columns
selected_columns = (
    loan_columns +
    customer_columns +
    credit_columns +
    payment_columns
)

# Keep only selected columns
loan_df = loan_df[selected_columns]

In [113]:
print("Shape:", loan_df.shape)
print("Columns:", len(loan_df.columns))
print(loan_df.columns.tolist())

Shape: (2260668, 38)
Columns: 38
['loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate', 'installment', 'purpose', 'loan_status', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc', 'verification_status', 'application_type', 'addr_state', 'zip_code', 'grade', 'sub_grade', 'dti', 'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc', 'acc_now_delinq', 'out_prncp', 'total_pymnt', 'total_rec_prncp', 'total_rec_int', 'recoveries', 'last_pymnt_d', 'last_pymnt_amnt', 'last_credit_pull_d', 'issue_d', 'total_rev_hi_lim']

In [118]:
loan_df.to_csv(
    r"C:\Users\henry\OneDrive\Desktop\LendingClub-Data-Pipeline\data\processed\clean_loan.csv",
    index=False
)


print("Clean dataset saved successfully.")

Clean dataset saved successfully.

In [130]:
loan_df["out_prncp"].sum()

np.float64(10051592040.29)

In [132]:
loan_df["loan_status"].value_counts()

loan_status
Fully Paid                                             1041952
Current                                                 919695
Charged Off                                             261655
Late (31-120 days)                                       21897
In Grace Period                                           8952
Late (16-30 days)                                         3737
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     31
Name: count, dtype: int64